---
- name: Initialize ansible mgmt host localy
  hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: Ensure group "ansible_admins" exists
    group:
      name: ansible_admins
      state: present

  - name: Create Ansible Admin user and Group
    user:
      name: "{{ qu_user_ansible_admin }}"
      comment: "local ansible admin"
      group: ansible_admins
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: Create folders with ownership
    file:
      state   : directory
      recurse : yes
      path    : "{{ item }}"
      owner: "{{ qu_user_ansible_admin }}"
      group: ansible_admins
      mode    : "0775"
    with_items:
    - "{{ qu_root_dir }}"
    - "{{ qu_dir_ansible }}/private"
    - "{{ qu_dir_ansible }}/private/playbooks"
    - "{{ qu_dir_inventory }}"
    - "{{ qu_dir_inventory }}/host_vars"
    - "{{ qu_roles_path }}"

  - name: Create Files that actually not exists
    file:
      state: touch
      path: "{{ item }}"
    with_items:
      - "{{ qu_dir_inventory }}/inventory.yml"
      - "{{ qu_dir_ansible }}/ansible.cfg"

  - name: Set environment variables (ANSIBLE_CONFIG)
    shell: echo "export ANSIBLE_CONFIG={{ qu_dir_ansible }}/ansible.cfg" >> /etc/profile.d/ansible_envs.sh

  - name: Set environment variables (A)
    shell: echo "export A={{ qu_root_dir }}/ansible/" >> /etc/profile.d/ansible_envs.sh

  - name: Get All Ansible Roles by definition in config file (Currently Static Value)
    shell: "curl -s {{ qu_roles_repo_search }}?per_page=1000 | grep -w clone_url | grep -o '[^\"]*\\.git' | grep {{ roles_repo_search }}"
    register: result

  - name: Parse Ansible Roles
    local_action: copy content={{result.stdout}} dest={{ dir_ansible }}/requirements.yml

  - name: write Ansible Roles to requirements.yml
    replace:
      path: "{{ qu_dir_ansible }}/requirements.yml"
      regexp: '^(.*)$'
      replace: '- src: \1'

  #- name: Install roles from Ansible Galaxy
  #  command: "ansible-galaxy install -r "{{ dir_ansible_requirements }}/requirements.yml" --ignore-errors"
  
  - name: fix file permissions
    file: 
      path: "{{ qu_root_dir }}" 
      owner: "{{ qu_user_ansible_admin }}"
      group: ansible_admins
      recurse: yes